# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Build and Test
        image: node:10.15.0
        caches:
          - node
        script:
          - npm install
          - npm test
  branches:
    master:
      - step:
          name: Build and Test
          script:
            - export IMAGE_NAME=safderun/bitbucket-website:$BITBUCKET_COMMIT
            - docker build -t ${IMAGE_NAME} .
            - docker login --username safderun --password $DOCKERHUB_TOKEN
            - docker push $IMAGE_NAME
          services:
            - docker
          caches:
            - docker
      # - step:
      #     name: Deploy to Production
      #     deployment: Production
      #     script:
      #       - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      #       - IMAGE_NAME=$BITBUCKET_REPO_SLUG
      #       - docker load --input "${IMAGE_NAME}.tar"
      #       - VERSION="prod-0.1.${BITBUCKET_BUILD_NUMBER}"
      #       - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
      #       - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
      #       - docker push "${IMAGE}:${VERSION}"
      #     services:
      #       - docker
