name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Gomplate
        run: |
          sudo curl -L -o /usr/bin/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.11.5/gomplate_linux-amd64
          sudo chmod +x /usr/bin/gomplate
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Bump version
        run: version=$(git describe --tags --abbrev=0) gomplate -f index.html.tmpl -o index.html
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64,darwin/amd64,darwin/arm64
          push: true
          tags: safderun/website:latest,safderun/website:${{ github.ref_name }}
